#!/usr/bin/env bash

#  PactSwiftMockService
#
#  Created by Marko Justinek on 19/8/21.
#  Copyright © 2021 Marko Justinek. All rights reserved.
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -euo pipefail

# ### Pre-requisites:
#
# `pact-reference` repo and `PactSwiftMockServer` repo are on the same folder level.
# Use the release tag for libpact_ffi-vX.X.X found at https://github.com/pact-foundation/pact-reference/releases
#
# ### Usage:
# ./Support/build_rust_dependencies libpact_ffi-v0.3.1
#
# ### Optional:
# To minimise the built binary size update $LIBPACT_FFI_DI/Cargo.toml and append the following:
#
# [lib]
# crate-type = ["staticlib"]
#
# [profile.release]
# opt-level = 'z'
# lto = true
# panic = 'abort'
#
#######################

if [[ -n "${DEVELOPER_SDK_DIR:-}" ]]; then
	# Assume we're in Xcode, which means we're probably cross-compiling.
	# In this case, we need to add an extra library search path for build scripts and proc-macros,
	# which run on the host instead of the target.
	# (macOS Big Sur does not have linkable libraries in /usr/lib/.)
	export LIBRARY_PATH="${DEVELOPER_SDK_DIR}/MacOSX.sdk/usr/lib:${LIBRARY_PATH:-}"

	# echo "🎉 ${SYSTEM_FRAMEWORK_SEARCH_PATHS}"
	# export SYSTEM_FRAMEWORK_SEARCH_PATHS="${DEVELOPER_SDK_DIR}/MacOSX.sdk/System/Library/Frameworks ${SYSTEM_FRAMEWORK_SEARCH_PATHS:-}"
	# echo "🎉 ${SYSTEM_FRAMEWORK_SEARCH_PATHS}"

	# source: https://github.com/TimNN/cargo-lipo/issues/41#issuecomment-774793892
fi

WORKSPACE=${GITHUB_WORKSPACE:-$PWD}
LIBPACT_FFI_DIR="${WORKSPACE}/../pact-reference/rust/pact_ffi"
CI=${CI:-"false"}
PACT_FOUNDATION_REPO="https://github.com/pact-foundation/pact-reference.git"
ACTIVE_ARCH=$(uname -m)

#######################
# Pre-requisite       #
#######################

# Check whether this script is being run in the right folder
if [ ! -d "$PWD/PactSwiftMockServer.xcodeproj" ]
then
	echo "🚨 Run this from the same folder where your 'PactSwiftMockServer.xcodeproj' lives."
	echo "ℹ You are runing it in $PWD"
	exit 1
fi

#######################
# Functions           #
#######################

function clonePactFFI {
	# Move a level up
	cd ..

	# Clone the pact-foundation/pact-reference repo
	echo "ℹ Cloning ${PACT_FOUNDATION_REPO} at release tag: $1"
	git clone --depth 1 -b $1 $PACT_FOUNDATION_REPO
}

#######################
# If CI               #
#######################

echo "👮‍♀️  Verifying project and dependencies' folder setup..."

if [[ "$CI" == true ]]; then
	# Check whether tag has been provided
	if [ $# -lt 1 ]; then
		echo "🚨  Missing libpact_ffi version tag!"
		echo "Please run something like ./build_rust_dependencies libpact_ffi-vX.X.X"
		exit 1
	fi
	clonePactFFI $1

elif [ ! -d "$PWD/../pact-reference" ]; then
	# Check whether tag has been provided
	if [ $# -lt 1 ]; then
		echo "🚨  Missing libpact_ffi version tag!"
		echo "Please run something like ./build_rust_dependencies libpact_ffi-vX.X.X"
		exit 1
	fi
	
	echo "⚠️ Missing pact-foundation/pact-reference repo"
	echo "ℹ Creating \"../pact-reference\" folder and cloning \"pact-reference\" repo"
	mkdir -p "$PWD/../pact-reference"
	clonePactFFI $1

else
	echo "ℹ Project setup seems to be in order."
fi

echo "ℹ Changing location to ${LIBPACT_FFI_DIR}"
cd $LIBPACT_FFI_DIR

#######################
# Setup               #
#######################

# Validate dependencies

echo "👮‍♀️  Checking if Rust is installed..."
if which cargo >/dev/null; then
	echo "cargo installed"
	CARGO_DIR=$(dirname "$( which cargo )")
	PATH=$PATH:$CARGO_DIR
elif command -v ~/.cargo/bin/cargo &> /dev/null; then
	echo "cargo installed in ~/.cargo/bin/"
	CARGO_DIR=$(dirname "$( command -v ~/.cargo/bin/cargo )")
	PATH=$PATH:$CARGO_DIR
else
	echo "🚨 Rust/Cargo not installed"
	echo "ERROR: cargo is required and is was found on this machine.\nInstall Rust using either homebrew:"
	echo "	curl https://sh.rustup.rs -sSf | sh"
	echo "or follow instructions at https://www.rust-lang.org/tools/install"
 	exit 1
fi

# Set the nightly toolchain
echo "ℹ Installing a nightly toolchain..."
rustup install nightly
rustup toolchain install nightly

echo "ℹ Setting nightly toolchain as default..."
rustup default nightly-x86_64-apple-darwin

# Add all the required triples
rustup target add \
	x86_64-apple-ios \
	aarch64-apple-ios
	
# Add the nightly toolchain that includes aarch64-apple-ios-sim
if [[ $ACTIVE_ARCH == "x86_64" ]]; then
	rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
else 
	rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
fi 

##############################################
# Build libpact_ffi binaries                 #
##############################################

echo "🏗  Building libpact_ffi.a for x86_64 iOS Simulator"
echo "cargo build --target=x86_64-apple-ios --release"
cargo build --target=x86_64-apple-ios --release

echo "🏗  Building libpact_ffi.a for arm64 iOS Simulator"
cargo +nightly build -Z build-std --target aarch64-apple-ios-sim --release

echo "🏗  Building libpact_ffi.a for arm64 iOS device"
echo "cargo build --target=aarch64-apple-ios --release"
cargo build --target=aarch64-apple-ios --release

echo "✅  libpact_ffi.a binaries built"

#######################
# Pact Mock Server    #
#######################

# Copy the compiled binaries into PactSwiftMockServer project
echo "🏗  Copying binaries to ${WORKSPACE}"

# Copy binary for an iOS device
echo "🚚  Copying arm64-ios (iOS device) binary..."
cp ../target/aarch64-apple-ios/release/libpact_ffi.a $WORKSPACE/Resources/iOS-device/libpact_ffi.a
echo "👍  Copied arm64-ios binary."

echo "🚚  Creating a fat binary for iOS Simulator (x86_64 and arm64)..."
lipo -create \
	../target/x86_64-apple-ios/release/libpact_ffi.a \
	../target/aarch64-apple-ios-sim/release/libpact_ffi.a \
	-output $WORKSPACE/Resources/iOS-simulator/libpact_ffi.a
echo "👍  Copied x86_64-ios and arm64-ios-sim fattie."

#######################
# Cleanup             #
#######################

echo "👍  Rust binaries for pact-ffi compiled and ready"
exit 0
