#!/usr/bin/env bash

#  Created by Marko Justinek on 2/6/22.
#  Copyright © 2022 Marko Justinek. All rights reserved.
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -euo pipefail

IOS_DEVICE_DIR="./Resources/XCFrameworks/libpact_ffi.xcframework/ios-arm64"
IOS_SIM_DIR="./Resources/XCFrameworks/libpact_ffi.xcframework/ios-arm64_x86_64-simulator"
MACOS_DIR="./Resources/XCFrameworks/libpact_ffi.xcframework/macos-arm64_x86_64"

rm $IOS_DEVICE_DIR/libpact_ffi.a
rm $IOS_SIM_DIR/libpact_ffi.a
rm $MACOS_DIR/libpact_ffi.a

echo ".keep" > $IOS_DEVICE_DIR/libpact_ffi.a
echo ".keep" > $IOS_SIM_DIR/libpact_ffi.a
echo ".keep" > $MACOS_DIR/libpact_ffi.a
