#!/usr/bin/env bash

#  PactSwiftMockService
#
#  Created by Marko Justinek on 19/8/21.
#  Copyright © 2021 Marko Justinek. All rights reserved.
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# upgrade
#
# 🚨🚨🚨 --- HOL' UP A MINUTE --- 🚨🚨🚨
#
# Make sure `pact-reference` and `PactSwiftMockServer` are siblings on the file system!
# Upgrades libpact_mock_server binaries and builds a fresh XCFramework
#

set -euo pipefail

# TODO: - This is Work in Progress

echo "🏗  Running ./Support/build_rust_dependencies"
echo "⚠️  Skipped..."
#./build_rust_depednecies

echo "🏗  Runing ./Support/build_xcframework"
echo "⚠️  Skipped..."
#./build_xcframework

echo "⚠️  Build and test the project, check `git status`, commit and push if all seems okay."
