#!/usr/bin/env bash

#  PactSwiftMockService
#
#  Created by Marko Justinek on 09/12/24.
#  Copyright © 2024 Marko Justinek. All rights reserved.
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -eu
set -o pipefail

SUPPORT_DIR="${BASH_SOURCE[0]%/*}/../.."
SRCROOT=${SRCROOT:-"."}
PATH="$PATH:/opt/local/bin:/opt/homebrew/bin/:/usr/local/bin"

function lint {
  if [ "${CI:-false}" == "true" ]; then
    echo "Skipping Xcode build phase SwiftLint as there is now a CI workflow for it."
  else
    # Note that the config file path needs to be specified relative to the $SRCROOT
    swiftlint lint \
      --no-cache \
      --config "${SUPPORT_DIR}/Configuration/swiftlint.yml" \
      --strict \
      "${SRCROOT}/Sources"
  fi
}

if command -v "swiftlint"; then
  lint
else
  echo "warning: swiftlint not installed! See https://github.com/realm/SwiftLint?tab=readme-ov-file#installation"
fi
