codecov:
  notify: {}
  require_ci_to_pass: true

comment:
  behavior: default
  layout: header, diff
  require_changes: false

coverage:
  precision: 2
  range:
  - 75.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true

ignore:
- (?s:Resources/.*/[^\/]+)\Z
- ^Resources.*
- (?s:Support/.*/[^\/]+)\Z
- ^Support.*

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
