#!/usr/bin/env bash
# shellcheck disable=SC1091

#  PactSwiftMockService
#
#  Created by Marko Justinek on 19/8/21.
#  Copyright © 2021 Marko Justinek. All rights reserved.
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -euo pipefail

# "import"
sourc "${BASH_SOURCE[0]%/*}/../utils.sh"

brew update

function brew_install {
  local tool="$1"
  if ! command -v "$tool" &> /dev/null; then
      echo -e "👎 $YELLOW$tool$NOCOLOR is not installed."
      echo -e "🍺 Installing $YELLOW$tool$NOCOLOR via Homebrew..."
      executeCommand "brew install $tool"
  else
      echo -e "👍 $LIGHT_BLUE$tool$NOCOLOR is already installed."
  fi
}

PACTSWIFTMOCKSERVER_TOOLS=(
  cbindgen
  doxygen
  xcbeautify
  swiftlint
)

for tool in "${PACTSWIFTMOCKSERVER_TOOLS[@]}"; do
  brew_install "$tool"
done
