name: Build (macOS 11, Xcode 12.4)

on:
  push:
    branches:
      - 'main'
      - 'chore/**'
      - 'docs/**'
      - 'feat/**'
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
      - 'releases/**'
      - 'style/**'
      - 'test/**'
      - 'tech/**'

jobs:
  test:
    name: Run tests
    runs-on: macos-11
    timeout-minutes: 60

    concurrency:
      group: test-${{ github.ref }}-${{ matrix.scheme }}
      cancel-in-progress: true

    strategy:
      fail-fast: true
      matrix:
        include:
          - scheme: "PactSwiftMockServer-iOS"
            destination: "platform=iOS Simulator,name=iPhone 12 Pro"
          - scheme: "PactSwiftMockServer-macOS"
            destination: "arch=x86_64"

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app

      - name: Prepare Tools
        run: |
          Support/prepare_build_tools
          Support/build_rust_dependencies

      - name: Run tests (Xcode)
        run: |
          ./Support/build_test

      - name: Upload code coverage
        run: |
          bash <(curl -s https://codecov.io/bash) -J 'PactSwiftMockServer'

  # after_success:
  #   name: Build PactSwift
  #   needs: [test]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Build demo projects
  #       run: |
  #         curl -X POST https://api.github.com/repos/surpher/PactSwift/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{ secrets.PACT_SWIFT_TOKEN }} --data '{"event_type":"PactSwiftMockServer - ${{ github.event.head_commit.message }}"}'
