name: Test Carthage build

on:
  push:
    branches:
      - 'main'
      - 'chore/**'
      - 'docs/**'
      - 'feat/**'
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
      - 'releases/**'
      - 'style/**'
      - 'test/**'
      - 'tech/**'

jobs:
  test:
    name: Run tests
    runs-on: macos-11

    strategy:
      fail-fast: true
      matrix:
        include:
          - scheme: "PactSwiftMockServer-iOS"
            destination: "platform=iOS Simulator,name=iPhone 13 Pro"
          - scheme: "PactSwiftMockServer-macOS"
            destination: "arch=x86_64"

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 13.2.1
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app

      - name: Prepare Tools
        run: |
          Support/prepare_build_tools

      - name: Validate Carthage
        run: |
          carthage build --no-skip-current --use-xcframeworks

#       - name: Run tests (Xcode)
#         run: |
#           ./Support/build_test
