name: "macOS 14"

on:
  workflow_call:
    inputs:
      rust-target-path:
        required: true
        type: string
      binaries-path:
        required: true
        type: string
      cache-key:
        required: true
        type: string
      cache-restore-key:
        required: true
        type: string
    secrets:
      codecov_token:
        required: true

env:
  DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

jobs:
  testMacOS14:
    name: "🖥️ macOS 14"
    runs-on: macos-14

    strategy:
      fail-fast: true
      matrix:
        include:
          - scheme: "PactSwiftMockServer-iOS"
            destination: "platform=iOS Simulator,name=iPhone 15 Pro"
          - scheme: "PactSwiftMockServer-macOS"
            destination: "" # Intentionally left empty

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}

    concurrency:
      group: test-macos14-${{ github.ref }}-${{ matrix.scheme }}
      cancel-in-progress: true

    steps:
      - name: "♻️ Checkout repository"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "♼ Cache rust binaries"
        uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.rust-target-path }}
            ${{ inputs.binaries-path }}
          key: ${{ inputs.cache-restore-key }}-${{ runner.os }}-${{ hashFiles('**/libpact_ffi.version') }}
          restore-keys: |
            ${{ inputs.cache-restore-key }}-${{ runner.os }}

      - name: "🛠  Prepare Tools"
        run: |
          sh Support/Scripts/CI/configure_build_tools

      - name: "⚗️  Run tests"
        run: |
          sh Support/Scripts/test
