name: "On macOS 14 (latest)"

on:
  workflow_call:
    inputs:
      rust-target-path:
        required: true
        type: string
      binaries-path:
        required: true
        type: string
      cache-key:
        required: true
        type: string
      cache-restore-key:
        required: true
        type: string
      submit-coverage-report:
        required: true
        type: boolean
    secrets:
      codecov_token:
        required: true
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer

jobs:
  testMacOS14:
    name: "⚗️  macOS (latest)"
    runs-on: macos-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - scheme: "PactSwiftMockServer-iOS"
            destination: "platform=iOS Simulator,name=iPhone 15 Pro"
            submit_code_coverage: true
          - scheme: "PactSwiftMockServer-macOS"
            destination: "arch=arm64"
            submit_code_coverage: true

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}

    concurrency:
      group: test-macos14-latest-${{ github.ref }}-${{ matrix.scheme }}
      cancel-in-progress: true

    steps:
      - name: "♻️ Checkout repository"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "♼ Cache rust binaries"
        uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.rust-target-path }}
            ${{ inputs.binaries-path }}
          key: ${{ inputs.cache-restore-key }}-${{ runner.os }}-${{ hashFiles('**/libpact_ffi.version') }}
          restore-keys: |
            ${{ inputs.cache-restore-key }}-${{ runner.os }}

      - name: "⚗️  Run tests"
        run: |
          sh Support/Scripts/Config/prepare_build_tools
          sh Support/Scrips/test

      - name: "⬆️  Upload coverage reports"
        if: ${{ matrix.submit_code_coverage && inputs.submit-coverage-report }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.codecov_token }}
          verbose: true
